baseURL = "https://labinitio.org/" 
languageCode = 'en-us'
title = 'Lab Initio'
theme = 'netlify-basic' # Still using netlify-basic theme here

[params]
  math = true # Math enabled under params

[markup] # Only one markup section
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true # Allow raw HTML rendering

