baseURL = "https://labinitio.org/" 
languageCode = 'en-us'
title = 'Lab Initio'
theme = 'netlify-basic'

[params]
  math = true

# Allow raw HTML rendering in markdown files
[markup.goldmark.renderer]
  unsafe = true
