# This is the main build configuration for your site
[build]
  # This tells Netlify where your serverless functions are located
  functions = "netlify/functions"

  # This is the command Netlify will run to build your site
  command = "hugo"

  # This is the directory that contains the final website files after the build
  publish = "public"

# This section defines environment variables specifically for the build process
[build.environment]
  HUGO_VERSION = "0.125.7"



